os: linux

jobs:
  include:
    - stage: test
      name: "./test-curdir.sh"
      script:
      - ./install.sh
      - cd ./.travis/ && bash ./test-curdir.sh
    - stage: test
      name: "./test-local-filepath.sh"
      script:
      - ./install.sh
      - cd ./.travis/ && bash ./test-local-filepath.sh
    - stage: test
      name: "./test-filepath.sh"
      script:
      - ./install.sh
      - cd ./.travis/ && bash ./test-filepath.sh
    - stage: test
      name: "./test-filedir.sh"
      script:
      - ./install.sh
      - cd ./.travis/ && bash ./test-filedir.sh
    - stage: test
      name: "./test-stdin.sh"
      script:
      - ./install.sh
      - cd ./.travis/ && bash ./test-stdin.sh
    - stage: test
      name: "./test-heredoc.sh"
      script:
      - ./install.sh
      - cd ./.travis/ && bash ./test-heredoc.sh
    - stage: test
      name: "./test-fallback-curdir.sh"
      script:
      - ./install.sh
      - cd ./.travis/ && bash ./test-fallback-curdir.sh

