os: linux
dist: bionic

stages:
  - verify_package
  - test

branches:
  only:
    - master

commonTestScript:
  - git checkout master # prevent travis from executing on a commit; otherwise git-buildbackage doesnt work
  - sudo ./gradlew assemble && sudo ./gradlew install
  - apt -f install
  - cd ./.travis/

jobs:
  include:
    - stage: verify_package
      name: "verify debian package"
      script:
      <<: commonTestScript
      - ./verify_debian-package.sh
    - stage: test
      name: "./test-curdir.sh"
      script:
      <<: commonTestScript
      - ./test-curdir.sh
    - stage: test
      name: "./test-local-filepath.sh"
      script:
      <<: commonTestScript
      - ./test-local-filepath.sh
    - stage: test
      name: "./test-filepath.sh"
      script:
      <<: commonTestScript
      - ./test-filepath.sh
    - stage: test
      name: "./test-filedir.sh"
      script:
      <<: commonTestScript
      - ./test-filedir.sh
    - stage: test
      name: "./test-stdin.sh"
      script:
      <<: commonTestScript
      - ./test-stdin.sh
    - stage: test
      name: "./test-heredoc.sh"
      script:
      <<: commonTestScript
      - ./test-heredoc.sh
    - stage: test
      name: "./test-fallback-curdir.sh"
      script:
      <<: commonTestScript
      - ./test-fallback-curdir.sh

