os: linux

stages:
  - verify_package
  - test

jobs:
  include:
    - stage: verify_package
      name: "verify debian package"
      script:
      - ./deb_install.sh
      - cd ./.travis/ && ./verify_debian-package.sh
    - stage: test
      name: "./test-curdir.sh"
      script:
      - ./install.sh
      - cd ./.travis/ && ./test-curdir.sh
    - stage: test
      name: "./test-local-filepath.sh"
      script:
      - ./install.sh
      - cd ./.travis/ && ./test-local-filepath.sh
    - stage: test
      name: "./test-filepath.sh"
      script:
      - ./install.sh
      - cd ./.travis/ && ./test-filepath.sh
    - stage: test
      name: "./test-filedir.sh"
      script:
      - ./install.sh
      - cd ./.travis/ && ./test-filedir.sh
    - stage: test
      name: "./test-stdin.sh"
      script:
      - ./install.sh
      - cd ./.travis/ && ./test-stdin.sh
    - stage: test
      name: "./test-heredoc.sh"
      script:
      - ./install.sh
      - cd ./.travis/ && ./test-heredoc.sh
    - stage: test
      name: "./test-fallback-curdir.sh"
      script:
      - ./install.sh
      - cd ./.travis/ && ./test-fallback-curdir.sh

