os: linux

jobs:
  include:
    - stage: test
      script:
      - ./install.sh
      - cd ./.travis/ && test-curdir.sh
    - stage: test
      script:
      - ./install.sh
      - cd ./.travis/ && test-local-filepath.sh
    - stage: test
      script:
      - ./install.sh
      - cd ./.travis/ && test-filepath.sh
    - stage: test
      script:
      - ./install.sh
      - cd ./.travis/ && test-filedir.sh
    - stage: test
      script:
      - ./install.sh
      - cd ./.travis/ && test-stdin.sh
    - stage: test
      script:
      - ./install.sh
      - cd ./.travis/ && test-heredoc.sh
    - stage: test
      script:
      - ./install.sh
      - cd ./.travis/ && test-fallback-curdir.sh

