#!/usr/bin/env bash
# vim:set noet sts=0 sw=4 ts=4:

help='usage: docker script [ path | string | << stdin ]

path: path to Dockerfile or to directory to a dockerfile
      can be omitted if Dockerfile is present in current directory

string: string representation of a Dockerfile, possibly as
        a result of `cat Dockerfile` command

stdin: Dockerfile passed from stdin or pipe, e.g. "cat Dockerfile | docker script"
       or "docker script << EOF..."
'
metadata='
{
     "SchemaVersion": "0.1.0",
     "Vendor": "https://github.com/stasmihailov/",
     "Version": "v0.1.0",
     "ShortDescription": "Dockerfile Runner for CLI"
}
'

case "$1" in
	docker-cli-plugin-metadata)
		echo "$metadata"
		exit
		;;
	help|-h|--help)
		echo "$help"
		exit
		;;
esac

cleanup() {
	local tag="$1"
	docker rm $(docker ps --all | grep "$tag" | awk '{print $1}')
	docker rmi "$tag"
}

run_from_file() {
	local dockerfile="$1"
	local tag
	tag="tmp_$(date +%N)" 
	docker build -t "$tag" "$dockerfile" $BUILD_ARGS && \
	docker run -it "$tag" $RUN_ARGS
	cleanup "$tag"
}

run_from_string() {
	local dockerfile="$1"
	local tag
	tag="tmp_$(date +%N)" 
	docker build -t "$tag" $BUILD_ARGS - <<< "$dockerfile" && {
	   	2>/dev/null docker run -it "$tag" || docker run "$tag" $RUN_ARGS
	}
	cleanup "$tag"
}

shift
script_path="$1"
shift

export BUILD_ARGS=""
export RUN_ARGS=""
for arg in $@; do
	case "$arg" in
		--build|-b)
			export BUILD_ARGS="$2"
			shift
			shift
			;;
		--run|-r)
			export RUN_ARGS="$2"
			shift
			shift
			;;
	esac
done

if [[ -f "$script_path/Dockerfile" ]]; then
	run_from_file "$script_path"
elif [[ -f "$script_path" ]]; then
	dockerfile="$(dirname "$script_path")"
	run_from_file "$dockerfile"
elif [[ -n "$script_path" ]]; then
	dockerfile="$script_path"
	run_from_string "$dockerfile"
elif [[ -f './Dockerfile' ]]; then
	run_from_file '.'
else
	__=""
	stdin=""
	read -r -N1 -t1 __  && {
		(( $? <= 128 )) && {
			IFS= read -rd '' stdin
			stdin="$__$stdin"
		}
	}

	if [[ -n "$stdin" ]]; then
		run_from_string "$stdin"
	else
		echo "$help"
	fi
fi

